### ISSUE TITLE
In navbar, provide the number associated with each "List" in parentheses

### ISSUE THREAD

**Issue by philipmjohnson** [HACC-Hui/HACC-Hui#106]
Please do work for this task in a branch called issue-105.

This would be a nice addition. Here's the current navbar:

<img width="1050" alt="Screen Shot 2020-10-27 at 7 43 10 AM" src="https://user-images.githubusercontent.com/290288/97340735-3f054300-1828-11eb-8681-3ef8941f9514.png">

It would be nice if, after an entry like "List Participants", there was the number of participants. For example, "List Participants (93)".

**Comment by jhsuP** [comment]
![image](https://user-images.githubusercontent.com/56209781/97362446-1fc8de80-1845-11eb-9a50-1fbacd4f5914.png)
