### ISSUE TITLE
"Best Fit Teams" --> "Open Teams"

### ISSUE THREAD

**Issue by philipmjohnson** [HACC-Hui/HACC-Hui#121]
Please do work for this task in a branch called issue-XXX.

The page title is misleading.  It leads you to believe that there are some other teams not being displayed that are not "Best Fit". 

Instead, Label this page "Open Teams".  Bonus points for indicating (small font) the number of closed teams.
<img width="1106" alt="Screen Shot 2020-10-29 at 12 27 15 PM" src="https://user-images.githubusercontent.com/290288/97639242-440df200-19e2-11eb-96f2-807f7e4059fc.png">

**Comment by cammoore** [comment]
Sorry, I fixed this is my issue.
