### ISSUE TITLE
Weird blank spaces between rows.

### ISSUE THREAD

**Issue by philipmjohnson** [HACC-Hui/HACC-Hui#122]
Please do work for this task in a branch called issue-XXX.

The table/grid is not layed out correctly.

<img width="1106" alt="Screen Shot 2020-10-29 at 12 27 15 PM" src="https://user-images.githubusercontent.com/290288/97639301-630c8400-19e2-11eb-8236-8c8c0495069d.png">

**Comment by cammoore** [comment]
Sorry, I finished this.
