### ISSUE TITLE
"Your Teams" page should also display teams you are a member of.

### ISSUE THREAD

**Issue by philipmjohnson** [HACC-Hui/HACC-Hui#123]
Please do work for this task in a branch called issue-XXX.

"Your teams" should include both the teams you own and the teams you are on.

<img width="1108" alt="Screen Shot 2020-10-29 at 12 29 46 PM" src="https://user-images.githubusercontent.com/290288/97639383-8800f700-19e2-11eb-8539-ce4f0b72d768.png">

**Comment by cammoore** [comment]
Sorry, I fixed this in my issue.
