### ISSUE TITLE
Update the NavBar to be mobile friendly.

### ISSUE THREAD

**Issue by cammoore** [HACC-Hui/HACC-Hui#51]
Please do work for this task in a branch called issue-51.

The current NavBar doesn't look good in mobile mode. It doesn't fit on the screen and isn't usable.

**Comment by jhsuP** [comment]
Sidebar was removed [here](https://github.com/HACC-Hui/HACC-Hui/commit/2a545187388725356fa77c99ea4284f38b5df769) and [here](https://github.com/HACC-Hui/HACC-Hui/commit/d023f93b934d9c4852a05f242d70e28b59486a11). Reopening so it can be added again.
