### ISSUE TITLE
Fix the errors on the ListParticipants page.

### ISSUE THREAD

**Issue by cammoore** [HACC-Hui/HACC-Hui#72]
Please do work for this task in a branch called issue-72.

Please fix the error and remove the console.logs from this page.
Warning: Failed prop type: Prop `trigger` in `Dropdown` conflicts with props: `selection`. They cannot be defined together, choose one or the other.
    in Dropdown (created by ListParticipantsCard)
    in ListParticipantsCard (created by ForwardRef)
    in ForwardRef (created by ListParticipantsWidget)
    in div (created by ItemGroup)
    in ItemGroup (created by ListParticipantsWidget)
    in div (created by GridColumn)
    in GridColumn (created by ListParticipantsWidget)
    in div (created by Grid)
    in Grid (created by ListParticipantsWidget)
    in ListParticipantsWidget (created by ForwardRef)
    in ForwardRef (created by ListParticipantsPage)
    in ListParticipantsPage (created by AllSubscriptionsHOC)
    in AllSubscriptionsHOC (created by ForwardRef)
    in ForwardRef (created by AllSubscriptionsHOC)
    in AllSubscriptionsHOC (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in Route (created by ProtectedRoute)
    in ProtectedRoute (created by App)
    in Switch (created by App)
    in div (created by SidebarPusher)
    in SidebarPusher (created by SideBar)
    in div (created by Segment)
    in Segment (created by SidebarPushable)
    in SidebarPushable (created by SideBar)
    in div (created by SideBar)
    in SideBar (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in withRouter(undefined) (created by App)
    in div (created by App)
    in div (created by App)
    in Router (created by HashRouter)
    in HashRouter (created by App)
    in App (created by AllSubscriptionsHOC)
    in AllSubscriptionsHOC (created by ForwardRef)
    in ForwardRef

**Comment by joshuahartmann** [comment]
this was fixed in issue-37
